// app/actions/email.ts
'use server'

import { Resend } from 'resend'
import { createClient as createSupabaseClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { generateInvoicePDF } from '@/lib/pdf-generator'

const resend = new Resend(process.env.RESEND_API_KEY)

const emailContent = {
  en: {
    subject: (invoiceNumber: string, seller: string) =>
      `Invoice ${invoiceNumber} from ${seller}`,
    greeting: (clientName: string) => `Dear ${clientName},`,
    intro: (invoiceNumber: string) =>
      `Please find attached invoice <strong>${invoiceNumber}</strong> for your review.`,
    detailsTitle: 'Invoice Details',
    invoiceNumber: 'Invoice Number:',
    issueDate: 'Issue Date:',
    dueDate: 'Due Date:',
    amount: 'Amount:',
    paymentDetailsTitle: 'Payment Details',
    bankAccount: 'Bank Account:',
    questions:
      "If you have any questions, please don't hesitate to contact us.",
    regards: 'Best regards,',
    footer: 'Generated by Invo - Bilingual invoicing for Polish freelancers',
  },
  pl: {
    subject: (invoiceNumber: string, seller: string) =>
      `Faktura ${invoiceNumber} od ${seller}`,
    greeting: (clientName: string) => `Szanowni Państwo ${clientName},`,
    intro: (invoiceNumber: string) =>
      `W załączniku przesyłam fakturę <strong>${invoiceNumber}</strong> do weryfikacji.`,
    detailsTitle: 'Szczegóły Faktury',
    invoiceNumber: 'Numer faktury:',
    issueDate: 'Data wystawienia:',
    dueDate: 'Termin płatności:',
    amount: 'Kwota:',
    paymentDetailsTitle: 'Dane do przelewu',
    bankAccount: 'Numer konta:',
    questions: 'W razie pytań proszę o kontakt.',
    regards: 'Pozdrawiam,',
    footer:
      'Wygenerowane przez Invo - Dwujęzyczne faktury dla polskich freelancerów',
  },
  no: {
    subject: (invoiceNumber: string, seller: string) =>
      `Faktura ${invoiceNumber} fra ${seller}`,
    greeting: (clientName: string) => `Kjære ${clientName},`,
    intro: (invoiceNumber: string) =>
      `Vennligst se vedlagt faktura <strong>${invoiceNumber}</strong> for gjennomgang.`,
    detailsTitle: 'Fakturadetaljer',
    invoiceNumber: 'Fakturanummer:',
    issueDate: 'Utstedelsesdato:',
    dueDate: 'Forfallsdato:',
    amount: 'Beløp:',
    paymentDetailsTitle: 'Betalingsdetaljer',
    bankAccount: 'Bankkonto:',
    questions: 'Ta gjerne kontakt hvis du har spørsmål.',
    regards: 'Med vennlig hilsen,',
    footer: 'Generert av Invo - Tospråklig fakturering for polske frilansere',
  },
}

export async function sendInvoiceEmail(
  invoiceId: string,
  recipientEmail: string,
  language: 'en' | 'pl' | 'no' = 'en'
) {
  const supabase = await createSupabaseClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .select(
      `
      *,
      clients (
        id,
        name,
        org_number,
        address
      )
    `
    )
    .eq('id', invoiceId)
    .eq('user_id', user.id)
    .single()

  if (invoiceError || !invoice) {
    return { error: 'Invoice not found' }
  }

  const { data: invoiceItems } = await supabase
    .from('invoice_items')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('sort_order')

  const { data: userProfile } = await supabase
    .from('user_profiles')
    .select('*')
    .eq('user_id', user.id)
    .single()

  try {
    const pdfBuffer = await generateInvoicePDF(
      invoice,
      invoiceItems || undefined,
      user.email || 'No email',
      userProfile
    )

    const lang = emailContent[language]
    const sellerName =
      userProfile?.business_name || userProfile?.full_name || user.email || ''

    const { data, error } = await resend.emails.send({
      from: `Invo <onboarding@resend.dev>`,
      to: recipientEmail,
      subject: lang.subject(invoice.invoice_number, sellerName),
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>${lang.subject(invoice.invoice_number, sellerName)}</h2>
          <p>${lang.greeting(invoice.clients?.name || '')}</p>
          <p>${lang.intro(invoice.invoice_number)}</p>
          
          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">${lang.detailsTitle}</h3>
            <table style="width: 100%;">
              <tr>
                <td style="padding: 8px 0;"><strong>${
                  lang.invoiceNumber
                }</strong></td>
                <td style="padding: 8px 0;">${invoice.invoice_number}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>${
                  lang.issueDate
                }</strong></td>
                <td style="padding: 8px 0;">${new Date(
                  invoice.issue_date
                ).toLocaleDateString()}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>${
                  lang.dueDate
                }</strong></td>
                <td style="padding: 8px 0;">${new Date(
                  invoice.due_date
                ).toLocaleDateString()}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>${lang.amount}</strong></td>
                <td style="padding: 8px 0; font-size: 18px; font-weight: bold;">
                  ${invoice.amount.toLocaleString('nb-NO', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2,
                  })} ${invoice.currency}
                </td>
              </tr>
            </table>
          </div>

          ${
            userProfile?.bank_account
              ? `
          <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h4 style="margin-top: 0;">${lang.paymentDetailsTitle}</h4>
            <p style="margin: 0;"><strong>${lang.bankAccount}</strong> ${userProfile.bank_account}</p>
          </div>
          `
              : ''
          }

          <p>${lang.questions}</p>
          
          <p>${lang.regards}<br>
          ${sellerName}</p>

          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">
          <p style="font-size: 12px; color: #666;">${lang.footer}</p>
        </div>
      `,
      attachments: [
        {
          filename: `Invoice_${invoice.invoice_number}.pdf`,
          content: pdfBuffer,
        },
      ],
    })

    if (error) {
      return { error: error.message }
    }

    return { success: true, messageId: data?.id }
  } catch (error) {
    console.error('Error sending email:', error)
    return { error: 'Failed to send email' }
  }
}
