// app/actions/email.ts
'use server'

import { Resend } from 'resend'
import { createClient as createSupabaseClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { generateInvoicePDF } from '@/lib/pdf-generator'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendInvoiceEmail(
  invoiceId: string,
  recipientEmail: string
) {
  const supabase = await createSupabaseClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  // Fetch invoice with client details
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .select(
      `
      *,
      clients (
        id,
        name,
        org_number,
        address
      )
    `
    )
    .eq('id', invoiceId)
    .eq('user_id', user.id)
    .single()

  if (invoiceError || !invoice) {
    return { error: 'Invoice not found' }
  }

  // Fetch invoice items
  const { data: invoiceItems } = await supabase
    .from('invoice_items')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('sort_order')

  // Fetch user profile
  const { data: userProfile } = await supabase
    .from('user_profiles')
    .select('*')
    .eq('user_id', user.id)
    .single()

  try {
    // Generate PDF using utility function
    const pdfBuffer = await generateInvoicePDF(
      invoice,
      invoiceItems || undefined,
      user.email || 'No email',
      userProfile
    )

    // Send email with PDF attachment
    const { data, error } = await resend.emails.send({
      from: `Invo <onboarding@resend.dev>`, // Change this when you verify your domain
      to: recipientEmail,
      subject: `Invoice ${invoice.invoice_number} from ${
        userProfile?.business_name || userProfile?.full_name || user.email
      }`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>Invoice ${invoice.invoice_number}</h2>
          <p>Dear ${invoice.clients?.name},</p>
          <p>Please find attached invoice <strong>${
            invoice.invoice_number
          }</strong> for your review.</p>
          
          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Invoice Details</h3>
            <table style="width: 100%;">
              <tr>
                <td style="padding: 8px 0;"><strong>Invoice Number:</strong></td>
                <td style="padding: 8px 0;">${invoice.invoice_number}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>Issue Date:</strong></td>
                <td style="padding: 8px 0;">${new Date(
                  invoice.issue_date
                ).toLocaleDateString()}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>Due Date:</strong></td>
                <td style="padding: 8px 0;">${new Date(
                  invoice.due_date
                ).toLocaleDateString()}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0;"><strong>Amount:</strong></td>
                <td style="padding: 8px 0; font-size: 18px; font-weight: bold;">
                  ${invoice.amount.toLocaleString('nb-NO', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2,
                  })} ${invoice.currency}
                </td>
              </tr>
            </table>
          </div>

          ${
            userProfile?.bank_account
              ? `
          <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h4 style="margin-top: 0;">Payment Details</h4>
            <p style="margin: 0;"><strong>Bank Account:</strong> ${userProfile.bank_account}</p>
          </div>
          `
              : ''
          }

          <p>If you have any questions, please don't hesitate to contact us.</p>
          
          <p>Best regards,<br>
          ${userProfile?.full_name || user.email}</p>

          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">
          <p style="font-size: 12px; color: #666;">Generated by Invo - Bilingual invoicing for Polish freelancers</p>
        </div>
      `,
      attachments: [
        {
          filename: `Invoice_${invoice.invoice_number}.pdf`,
          content: pdfBuffer,
        },
      ],
    })

    if (error) {
      return { error: error.message }
    }

    return { success: true, messageId: data?.id }
  } catch (error) {
    console.error('Error sending email:', error)
    return { error: 'Failed to send email' }
  }
}
